INSERT INTO users (name, email, password) 
VALUES 
('Devin Sanders', 'tristanjacobs@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Iva Harrison', 'allisonjackson@mail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Mamie Webster', 'ianhale@ymail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

INSERT INTO properties (title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
VALUES 
('Daily every', 'Sick foot brain express truth sure written exclaimed entire ability next treated store coast tail kept coast sheet symbol zulu gradually season southern oxygen than appropriate title see work making draw plates canal contrast whom page five rocky evidence operation active steam yesterday hurt earlier movement branch dig some light peace parent fighting driving memory variety final replace catch monkey born shape brush brown fewer wore duty show direct mood quarter spread opportunity salmon paint cool school blew mail toy about thrown pond bottom burst gasoline taught driver great tropical is brother human hurried truck top tin nodded skin breathe world fat than dust origin slow dust tired harder summer point underline sides equal birthday dig brass around me lungs to tent word definition fair equator grow seems duck feathers examine song ten direction stage tax happily eye using pitch forward memory mad captured into low advice officer judge he onto breakfast verb attached gave discovery managed ran faster ago enemy train guard park welcome everybody excited skill date recall hot nervous examine first pilot house select clothes alone policeman play join steel weak like first pony danger aware of prevent steel further throat has leaving ordinary operation got gain week ill ill diameter composition milk select seed there sheep year spin some memory mysterious sides trap walk composed possible lungs good peace measure gradually rise service frozen inch dog love apart became oldest song customs number bottom outline office married plural reason structure stock someone worse must creature ready gently fireplace us court mill vessels very grade gradually simplest escape harbor excellent community control tired him create suggest pine sun principal start worker organized began food choice until subject putting tube fair spider typical eat known total difficulty forget expression shore develop important condition adjective universe production shade train', 103, 'https://images.pexels.com/photos/2088258/table-dining-room-chair-dining-area-2088258.jpeg', 'https://images.pexels.com/photos/2088258/table-dining-room-chair-dining-area-2088258.jpeg?auto=compress&cs=tinysrgb&h=350', 2438, 8, 2, 1, true, 'Prince Edward Island', 'Charlottetown', 'Canada', '1716 Misih Highway', '48752'),
('Magic familiar', 'Comfortable fill stick belong fly construction wave positive mean gently happy alone event thousand wore sick rope fighting typical popular nuts built swept particular eye salmon rate explain follow adventure outline dish library heart strength selection pocket teeth production bread everybody luck stage hundred atomic forgotten drove am found forget similar social thousand mass breathe border touch box suit pull into receive felt higher flat question tip slide nearly since branch society herd hurt without ever zoo stuck laugh tomorrow own fall position judge structure new danger mean pig lower steel have weak great either make body long hurry vegetable kept together east straw muscle get broad torn rocket total tribe waste thus careful sentence camera lonely horse doctor spite deeply sudden using rising bag graph pond pine bicycle likely studied rocky near twelve return again film pan dull offer roll effect bone customs wonderful rain gas sets organization bowl coat decide wild remarkable paragraph another check question afternoon helpful climate news bring instrument dozen wing yes aloud stone red eight image door thick us suit particles fall purpose everything perhaps wood basis root difficulty managed safe high dry equal height mainly plain lead grandfather numeral egg attached pleasure shallow did pot closely person right mathematics law tears grandfather driving species forest speech between studying fix twenty lovely brush transportation pink raise coast is grandfather throw exchange fur likely practical apartment massage highest interior slept view vowel weak cave information dug count who political band held top grandmother cause were whenever fed unit expect aid earlier neighborhood series does been certainly simply example cloth thus reach next know right anywhere partly to principle your effect get rhyme minute warn cold finger read dig sweet pride split soon dot hungry taste everything swam crack difficulty closer trunk spend hill consider mother', 128, 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg', 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg?auto=compress&cs=tinysrgb&h=350', 36317, 1, 3, 0, true, 'Quebec', 'Chicoutimi', 'Canada', '1950 Zujcol Path', '19755'),
('List least', 'Younger week student surface speak how sick bark outside combine wide thou improve recent plane soon behavior teacher tape adult pencil remain bear laugh free spin make stick victory picture wheat successful near correctly swept steep lake chapter card film telephone identity brick lucky electricity solar captain rest surprise worth folks caught example larger headed sugar symbol represent handle dot spell straw barn plate among party long fix fifteen had show chain way religious rest afternoon bat accurate behavior bigger term exact hang without him garden yet fur spirit cut bright money plus eight birthday composition soil she minute industrial silk hair herd chief silence temperature thought teacher show signal eye grew deal conversation tank castle energy empty cast carbon care western climate zipper cloth moving lovely shot brush angry ready popular zebra definition grabbed matter leaf picture pipe make paid away refused year service proud balance water fish road massage highway instance yes some doctor board happily here fog plates upon finger secret form fifty sets forth winter bone flag age bottle native whatever should bat farther far local frighten green scientist shoe old finally managed article become equator funny forgot coach happy manner range village baseball tired nuts cat slowly possibly motor develop move found crowd blue aware action may two changing pitch final stick sides sea rear hunt pet handle simple by ought rest machine who spread setting standard too street smallest us extra wear terrible dust ourselves animal underline him unusual contain happily red nearer storm bag ship trouble skin outline pattern among avoid wolf suit brain too doll pig atmosphere warm future society planned nearer lift me storm capital building applied effect cotton share clay report heat around nose sum aware as pot question spend respect equal hill slide independent fully children shorter fed energy', 391, 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg', 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg?auto=compress&cs=tinysrgb&h=350', 34565, 0, 1, 1, true, 'Newfoundland And Labrador', 'Paradise', 'Canada', '1848 Cuzo Trail', '08409');

INSERT INTO reservations (id, guest_id, property_id, start_date, end_date) 
VALUES 
(1009999, 743, 114, '2022-09-30', '2022-10-15'),
(1010000, 269, 841, '2021-04-30', '2021-05-18'),
(1010001, 667, 708, '2021-08-22', '2021-08-23');

NSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) 
VALUES 
(328, 190, 1015655, 4, 'Sigkez amafozuz zidak cirazke giikeak lazup cefumzeb ohefcob vugsi vudavi ahevi awogi tagjowos.'),
(340, 769, 1013720, 5, 'Filin alforec pad sevopa ej jesebfuh tap ma ajafihjoc pujawoso kuez zitu sebfal zialuti jool rudpi gogofiri da.'),
(891, 290, 1016559, 3, 'Hawapel pasale udmupnej co uzfos novuhig bilad dedgure vim renfef soumi suti bop.');